# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Coderise.OKF4net
PackageVersion: 0.6.0
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: okf.exe
  PortableCommandAlias: okf
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jchable/okf4net/releases/download/v0.6.0/okf-0.6.0-win-x64.zip
  InstallerSha256: 9518D8356BA216152FE4CF6838041B70874B378FD07756DABF30D6E0DCADC504
- Architecture: arm64
  InstallerUrl: https://github.com/jchable/okf4net/releases/download/v0.6.0/okf-0.6.0-win-arm64.zip
  InstallerSha256: 307A8E9EF45CCF964112448643418E7E96CCECF98E759687CDB8DAFA8EBC11FD
ManifestType: installer
ManifestVersion: 1.12.0
